project:
  type: website

website:
  title: "Derrick"

  navbar:

    search: true
    left:
      - text: Publications
        file: publications/publications.qmd

      - text: Presentations
        file: presentations/presentations.qmd

      - text: List
        file: list/Awesome.qmd

    right:

      - icon: github
        href: https://github.com/d-chambers
        aria-label: Derrick Chambers GitHub



format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    grid:
      body-width: 1100px
      sidebar-width: 200px
      margin-width: 200px
    resources:
      - _files/*
