---
title: "Awesome List"
---

This is an [awesome list](https://github.com/topics/awesome-list) of things I think people should know about.

## Math

- [DFT Scaling](https://appliedacousticschalmers.github.io/scaling-of-the-dft/AES2020_eBrief/) :
    A succinct explanation of the scaling of the DFT and the associated units.

- [Better explained](https://betterexplained.com/archives/) : Helpful articles on various mathematical topics.

## Documentation

- [Quarto](https://quarto.org/) : A framework for building technical documentation in many forms (including this website).

- [Awesome Quarto](https://github.com/mcanouil/awesome-quarto) : A list of quarto related projects / packages.

- [FDSN docs](https://docs.fdsn.org): Excellent documentation on various seismic formats and theory.

## Software

- [DASCore](https://dascore.org/) : A Python library for distributed fiber optic sensing.

- [DASPy](https://github.com/HMZ-03/DASPy) : A Python toolbox for distributed acoustic sensing data processing.

- [XDAS](https://github.com/xdas-dev/xdas) : A Python framework for distributed acoustic sensing (DAS).

- [Orange](https://orangedatamining.com/) : Open-source graphical machine learning and data mining software.


## Geology

- [USGS Geolex](https://ngmdb.usgs.gov/Geolex/search) : A lookup for various geological formations.
